### ISSUE TITLE
作者用多久完成了组件库

### ISSUE THREAD

**Issue by Mirror198829** [BboyAwey/admin-ui#1]
很好奇作者一个人 用了多久完成了组件库编写呢？？？

**Comment by BboyAwey** [comment]
Half time，一年半的时间。实际上如果全职开发，目前这些功能预计最多9个月时间就能全部完成。组件库实际上是需要持续迭代和维护的，没有尽头。你可以看看antD他们一直在叫苦说维护人力短缺，实际上就是这原因。
